### ISSUE TITLE
ToDo for First Release

### ISSUE THREAD

**Issue by Woohoopy** [Woohoopy/WarThunderCalculator#5]
- [x] Double/Integer Restriction to text field
- [x] Keyboard interactivity  #2 along with 'return'=='go!' 
- [x] Fixed size text fields
- [x] Brighter font inside of text fields (orange)
