### ISSUE TITLE
Todo for 0.9.1

### ISSUE THREAD

**Issue by Woohoopy** [Woohoopy/WarThunderCalculator#6]
- [x] Add 'return' button for keyboard 
- [x] Add spacer between 'Total Rating' and textboxes
- [x] Fix header to look like original
- [x] Obtain better resolution loading screen image
- [x] Change font color of telemetry
