### ISSUE TITLE
ToDo for 0.9.2

### ISSUE THREAD

**Issue by Woohoopy** [Woohoopy/WarThunderCalculator#7]
- [x] Adjust cover image to include Gaijin logo
- [x] Remove excessive image files
- [x] Perhaps add a warning for users to only place TOP three planes
- [x] Add App Logo
- [x] Have keyboard/background move down when user is on last box
