### ISSUE TITLE
ToDo for Version 1.0

### ISSUE THREAD

**Issue by Woohoopy** [Woohoopy/WarThunderCalculator#8]
- [x] Check UI compatibility for Iphone 5/5S
- [x] Check UI compatibility for Iphone 6
- [x] Check UI compatibility for Iphone 6+
